openapi: 3.0.0
info:
  title: 'Search API'
  version: 1.0.0
servers:
- url: http://localhost/NuclearGitProject/Nuclear-Power-Plant
paths:
  /users/login:
    post:
      summary: 'User login in the application'
      description: 'If both values are correct, then the user gets logged,
                    otherwise he will be told that either the password or
                    the username are incorrect'
      tags: 
        - 'users'
      requestBody:
        description: 'Necessary infomation for the login of a user'
        required: true
        content:
          application/json:
            schema:
                properties:
                    username:
                      type: string
                    password:
                      type: string
      responses:
        '200':
          description: Success
        '404':
          description: Resource Not Found
  /users/register:
    post:
      summary: 'User register in the application'
      description: 'If all the required data is valid, a new account is created'
      tags: 
        - 'users'
      requestBody:
        description: 'Necessary infomation for the login of a user'
        required: true
        content:
          application/json:
            schema:
                properties:
                    username:
                      type: string
                    password:
                      type: string
                    
      responses:
        '200':
          description: Success
        '404':
          description: Resource Not Found    
  
  /Emails/sendMail:
    post:
      tags: 
        - 'Emails'
      parameters: 
        - in: query
          name: to
          required: true
          schema:
            type: string
        - in: query
          name: title
          required: true
          schema:
            type: string
        - in: query
          name: message
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /PowerPlants/insert:
    post:
      tags: 
          - 'PowerPlants'
      parameters: 
          - in: query
            name: author_id
            required: true
            schema:
              type: integer
          - in: query
            name: name
            required: true
            schema:
              type: string
          - in: query
            name: reactorCount
            required: true
            schema:
              type: integer
          - in: query
            name: reactorPower
            required: true
            schema:
              type: string
          - in: query
            name: altitude
            required: true
            schema:
              type: integer
          - in: query
            name: latitude
            required: true
            schema:
              type: integer
          - in: query
            name: longitude
            required: true
            schema:
              type: integer
      responses:
          '200':
            description: Success
          '400':
            description: Bad Request
  /PowerPlants/update:
    patch:
      tags: 
        - 'PowerPlants'
      parameters: 
        - in: query
          name: id
          required: true
          schema:
            type: integer
        - in: query
          name: name
          required: true
          schema:
            type: string
        - in: query
          name: reactorCount
          required: true
          schema:
            type: integer
        - in: query
          name: reactorPower
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /PowerPlants/getById:
    get:
      tags: 
        - 'PowerPlants'
      parameters: 
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /PowerPlants/getByName:
    get:
      tags: 
        - 'PowerPlants'
      parameters: 
        - in: query
          name: name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /PowerPlants/getAll:
    get:
      tags: 
        - 'PowerPlants'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /PowerPlants/delete:
    delete:
      tags: 
        - 'PowerPlants'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /Configurations/health:
    get:
      tags: 
        - 'Configurations'
      parameters: 
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /Configurations/weather:
    get:
      tags: 
        - 'Configurations'
      parameters: 
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /Configurations/info:
    get:
      tags: 
        - 'Configurations'
      parameters: 
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /States/insert:
    post:
      tags: 
        - 'States'
      parameters: 
        - in: query
          name: id_centrala
          required: true
          schema:
            type: integer
        - in: query
          name: temepratura_nucleu
          required: true
          schema:
            type: integer
        - in: query
          name: putere_racire
          required: true
          schema:
            type: integer
        - in: query
          name: putere_produsa
          required: true
          schema:
            type: integer
        - in: query
          name: putere_ceruta
          required: true
          schema:
            type: integer
        - in: query
          name: putere_energie
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
    put:
      tags: 
        - 'States'
      parameters: 
        - in: query
          name: id_centrala
          required: true
          schema:
            type: integer
        - in: query
          name: temepratura_nucleu
          required: true
          schema:
            type: integer
        - in: query
          name: putere_racire
          required: true
          schema:
            type: integer
        - in: query
          name: putere_produsa
          required: true
          schema:
            type: integer
        - in: query
          name: putere_ceruta
          required: true
          schema:
            type: integer
        - in: query
          name: putere_energie
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /States/info:
    get:
      tags: 
        - 'Configurations'
      parameters: 
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
  /States/central:
    get:
      tags: 
        - 'Configurations'
      parameters: 
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          
          
          
